/*
var lowercaseBox = document.getElementById("lowercase");
var uppercaseBox = document.getElementById("uppercase");
var numericBox = document.getElementById("numeric");
var specialBox = document.getElementById("special");
*/


// password output element
var result = document.getElementById("password");

// generate button element
var generateBtn = document.getElementById("generateBtn");


// main function (encompasses all parts of the generation process)
function generatePW() {
    
    // amount of characters
    function checkAmount() {
        var charLength = document.getElementById("length");
        if (charLength < 8 || charLength > 58) {
            alert("please enter a valid amount of characters.")
        }
    };

    // take checked boxes and add to dynamic array that adds each box together to be randomized later 
    
    // error if no character types are selected
    function isChecked() {
        if (
            (document.getElementById("lowercase").checked = false)
            && (document.getElementById("uppercase").checked = false)
            && (document.getElementById("special").checked = false)
            && (document.getElementById("numeric").checked = false)
            ) {
                alert("please check at least one box.")
        }
    };
        
    // get proper number of characters
    // (take input number and use that to determine how many times you need to loop through the array)
    
    
    // combine checked boxes with number of characters to generate final password
    
    // take all randomized values and place them all together in a random order
    
    // store data generated by the user for each character type they select
    
    // loop through each array, pick random values (depends on input #, includes all checked boxes)
    


    // pick a random value from the array [working]
    function specialGen(special) {
        //if (document.getElementById("special").checked = true) {
            var special = ["!", "?", "&", "#", "@", "*", "_", "-", "."];
            var randomSpecial = special[Math.floor(Math.random() * special.length)];
            console.log(randomSpecial);
            //}
        };
        
        function numericGen(numeric) {
            var numeric = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];
            var randomNumeric = numeric[Math.floor(Math.random() * numeric.length)];
            console.log(randomNumeric);
        };
        
        function lowercaseGen(lowercase) {
            var lowercase = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"];
            var randomLowercase = lowercase[Math.floor(Math.random() * lowercase.length)];
            console.log(randomLowercase);
        };
        
        function uppercaseGen(uppercase) {
            var uppercase = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"];
            var randomUppercase = uppercase[Math.floor(Math.random() * uppercase.length)];
            console.log(randomUppercase);
        };
        
        checkAmount();
        isChecked();
        specialGen();
        numericGen();
        lowercaseGen();
        uppercaseGen();
        
    };
    
    // generate that password!
    generatePW();

    
    // var range = ("8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58");
