// one object with many variables (arrays)
const characterTypes = {
    special: ["!", "?", "&", "#", "@", "*", "_", "-", "."],
    numeric: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
    lowercase: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"],
    uppercase: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"],
    range: ["8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58"]
};
      // linked to HTML
const lowercaseIn = document.getElementById("lowercase");
const uppercaseIn = document.getElementById("uppercase");
const numericIn = document.getElementById("numeric");
const specialIn = document.getElementById("special");

const generate = document.getElementById("generateBtn");


// all of these generate a random number from the array they're calling
const genSpecial = (Math.floor(Math.random() * special.length));
const genNumeric = (Math.floor(Math.random() * numeric.length));
const genLowercase = (Math.floor(Math.random() * lowercase.length));
const genUppercase = (Math.floor(Math.random() * uppercase.length));


console.log(genSpecial);
console.log(genNumeric);
console.log(genLowercase);
console.log(genUppercase);


// random number generators
function gSpecial(){
    (Math.floor(Math.random() * special.length));
}
function gNumeric(){
   (Math.floor(Math.random() * special.length));
}

function gLowercase(){
    (Math.floor(Math.random() * special.length));
}
function gUppercase(){
    (Math.floor(Math.random() * special.length));
}
function gRange(){
    (Math.floor(Math.random() * special.length));
}

function password(){
    generateBtn.addEventListener("submit", button,)
        (characterTypes(Math.floor(Math.random)));
}

/* 
----- Notes to Self -----

2 for loops?
need error message when character type isn't selected or number 
isn't between 8-128 [range is currently 8-58 until i figure out how 
to do it more effectively. perhaps character codes.]

use:
math.random
math.floor
.addeventlistener

user inputs:
1) number 8-128
2) checkboxes, four types, at least one needed
    - special
    - numeric
    - lowercase
    - uppercase
3) click the generate PW button

need to store data generated by the user for each character type selected, 
then take those values and randomize them all together
*/