// listen for a click on generateBtn to generate the password (run function generatePW) [working]
function whenClicked() {
    document.getElementById("generateBtn").addEventListener("click", generatePW);

    // main function - run when generateBtn is clicked [working]
    function generatePW() {

        // get a random value from whatever box is checked [working]
        function generateChecked() {
            // empty array that will store which boxes are checked [working]
            var boxesArray = [];
            
            // if box is checked, pull a random value from array
            if (document.getElementById("special").checked) {
                boxesArray.push("special")
                var special = ["!", "?", "&", "#", "@", "*", "_", "-", "."]; // 9 characters
                var specialNum = special[Math.floor(Math.random() * special.length)];
                console.log("special checked")
                console.log(specialNum);
            } else {
                console.log("special no")
            };
            
            
            if (document.getElementById("numeric").checked) {
                boxesArray.push("numeric")
                var numeric = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]; // 10 characters
                var numericNum = numeric[Math.floor(Math.random() * numeric.length)];
                console.log("numeric checked")
                console.log(numericNum);
            } else {
                console.log("numeric no");
            };
            
            
            if (document.getElementById("lowercase").checked) {
                boxesArray.push("lowercase")
                var lowercase = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]; // 26 characters
                var lowercaseNum = lowercase[Math.floor(Math.random() * lowercase.length)];
                console.log("lowercase checked");
                console.log(lowercaseNum);
            } else {
                console.log("lowercase no");
            };
            
            
            if (document.getElementById("uppercase").checked) {
                boxesArray.push("uppercase")
                var uppercase = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]; // 26 characters
                var uppercaseNum = uppercase[Math.floor(Math.random() * uppercase.length)];
                console.log("uppercase checked")
                console.log(uppercaseNum);
            } else {
                console.log("uppercase no")
            };

            console.log(boxesArray);
        };
        generateChecked();

        // errors to give if neccessary [working]
        function error() {

            // error for incorrect length input [working]
            function invalidLength() {
                var charLength = document.getElementById("length").value;
                if (charLength >= 8 && charLength <= 58) {
                    console.log("nice, you entered a good number")
                } else {
                    console.log("no! bad number!");
                };
            };
            invalidLength();

            // error for no character type selected [working]
            function notChecked() {
                var numYes = document.getElementById("numeric").checked;
                var lowerYes = document.getElementById("lowercase").checked;
                var upperYes = document.getElementById("uppercase").checked;
                var specialYes = document.getElementById("special").checked;

                if (
                    !numYes
                    && !lowerYes
                    && !upperYes
                    && !specialYes
                    ) {
                    console.log("check a goddamn box you heathen")
                } else {
                    console.log("box checked");
                };
            };
            notChecked();

        };
        error();

    };   
    generatePW(); 

};
whenClicked();



// take input number and use that to determine how many times you need to loop through the array
// combine checked boxes with number of characters to generate final password [total number of items in each array in a loop?]
// store data generated by the user for each character type they select
// loop through each array, pick random values (depends on input #, includes all checked boxes)

// var result = document.getElementById("password");
// var range = ("8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58");

